### ISSUE TITLE
"no Babel required any more" ??

### ISSUE THREAD

**Issue by alexhumanbean** [xuqingkuang/react-redux-boilerplate#5]
Hi, you wrote "no Babel required any more", but there is an issue with ES6 - "npm start":

_____________
\node_modules\webpack-polyfill-service-plugin\no
de_modules\polyfill-service\lib\index.js:175
                        explainerComment.push(...sortedFeatures
                                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
----------------

So Babel is REQUIRED??

**Comment by xuqingkuang** [comment]
Please provide more informations.

I recommend you to update npm to latest version with `npm install -g npm` at first, and remove `node_modules` folder, then reinstall the dependencies.

**Comment by xuqingkuang** [comment]
Close first, more responses are welcome.
